- type: entity
  id: PhotocopierMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: копировальный аппарат (машинная плата)
  description: Из этой машинной платы собирается копировальный аппарат.
  components:
    - type: Sprite
      state: science
    - type: MachineBoard
      prototype: PhotocopierBase
      stackRequirements:
        Plastic : 5
        Steel : 5

- type: entity
  id: GeneratorRTGMachineCircuitboard
  parent: BaseMachineCircuitboard
  name: РИТЭГ (машинная плата)
  description: Из этой машинной платы собирается РИТЭГ.
  components:
  - type: Sprite
    state: engineering
  - type: MachineBoard
    prototype: GeneratorRTG
    stackRequirements:
      Manipulator: 5
      Steel: 10
      Plastic: 5
      Gold: 10
      Silver: 10
      CableHV: 5
      Uranium: 30
      Diamond: 1

- type: entity
  id: BaseMachineCircuitboardTypan
  parent: BaseItem
  name: машинная плата
  abstract: true
  suffix: Тайпан
  components:
  - type: MachineBoard
  - type: Sprite
    sprite: _Mini/Objects/Misc/module.rsi
    state: syndicate
  - type: Item
    storedRotation: -90
  - type: StaticPrice
    price: 100
  - type: PhysicalComposition
    materialComposition:
      Glass: 230
    chemicalComposition:
      Silicon: 20

- type: entity
  id: AutolatheMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: автолат (машинная плата)
  description: Печатная плата автолата.
  components:
  - type: MachineBoard
    prototype: AutolatheTypan
    stackRequirements:
      Manipulator: 4
      Glass: 1

- type: entity
  id: AutolatheHyperConvectionMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: гиперконвекционный автолат (машинная плата)
  description: Печатная плата гиперконвекционного автолата.
  components:
  - type: MachineBoard
    prototype: AutolatheHyperConvectionTypan
    stackRequirements:
      Manipulator: 3
      Glass: 1
    tagRequirements:
      Igniter:
        amount: 1
        defaultPrototype: Igniter

- type: entity
  id: ProtolatheMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: протолат (машинная плата)
  description: Печатная плата протолата.
  components:
  - type: MachineBoard
    prototype: ProtolatheTypan
    stackRequirements:
      Manipulator: 4
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker

- type: entity
  id: ProtolatheHyperConvectionMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: гиперконвекционный протолат (машинная плата)
  description: Печатная плата гиперконвекционного протолата.
  components:
  - type: MachineBoard
    prototype: ProtolatheHyperConvectionTypan
    stackRequirements:
      Manipulator: 4
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
      Igniter:
        amount: 1
        defaultPrototype: Igniter

- type: entity
  id: CircuitImprinterMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: принтер схем (машинная плата)
  description: Печатная плата принтера схем.
  components:
  - type: MachineBoard
    prototype: CircuitImprinterTypan
    stackRequirements:
      Manipulator: 2
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker

- type: entity
  id: CircuitImprinterHyperConvectionMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: гиперконвекционный принтер схем (машинная плата)
  description: Печатная плата гиперконвекционного принтера схем.
  components:
  - type: MachineBoard
    prototype: CircuitImprinterHyperConvectionTypan
    stackRequirements:
      Manipulator: 2
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker
      Igniter:
        amount: 1
        defaultPrototype: Igniter

- type: entity
  id: ExosuitFabricatorMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: фабрикатор экзокостюмов (машинная плата)
  description: Печатная плата фабрикатора экзокостюмов.
  components:
  - type: MachineBoard
    prototype: ExosuitFabricatorTypan
    stackRequirements:
      Manipulator: 4
      Glass: 5

- type: entity
  id: UniformPrinterMachineCircuitboardTypan
  parent: BaseMachineCircuitboard
  name: принтер униформы (машинная плата)
  description: Печатная плата принтера униформы.
  components:
  - type: MachineBoard
    prototype: UniformPrinterTypan
    stackRequirements:
      Manipulator: 3

- type: entity
  id: ResearchAndDevelopmentServerMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: сервер РнД (машинная плата)
  description: Печатная плата сервера РнД.
  components:
  - type: MachineBoard
    prototype: ResearchAndDevelopmentServerTypan
    stackRequirements:
      Plasma: 5

- type: entity
  id: CargoTelepadMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: грузовой телепад (машинная плата)
  description: Печатная плата грузового телепада.
  components:
  - type: MachineBoard
    prototype: CargoTelepadTypan
    stackRequirements:
      Manipulator: 2
      Steel: 5

- type: entity
  id: BiofabricatorMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: фабрикатор биокубов (машинная плата)
  description: Печатная плата фабрикатора биокубов.
  components:
  - type: MachineBoard
    prototype: BiofabricatorTypan
    stackRequirements:
      Manipulator: 4
      Glass: 1

- type: entity
  id: WeaponryTechFabCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: оружейный ТехФаб (машинная плата)
  description: Печатная плата оружейного ТехФаба.
  components:
  - type: MachineBoard
    prototype: WeaponryTechFabTypan
    stackRequirements:
      Manipulator: 4
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker

- type: entity
  id: MedicalTechFabCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: медицинский ТехФаб (машинная плата)
  description: Печатная плата медицинского ТехФаба.
  components:
  - type: MachineBoard
    prototype: MedicalTechFabTypan
    stackRequirements:
      Manipulator: 4
    tagRequirements:
      GlassBeaker:
        amount: 2
        defaultPrototype: Beaker

- type: entity
  id: OreProcessorMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: переработчик руды (машинная плата)
  components:
  - type: MachineBoard
    prototype: OreProcessorTypan
    stackRequirements:
      Manipulator: 4
      Glass: 1

- type: entity
  parent: BaseMachineCircuitboardTypan
  id: OreProcessorIndustrialMachineCircuitboardTypan
  name: промышленный переработчик руды (машинная плата)
  components:
  - type: MachineBoard
    prototype: OreProcessorIndustrialTypan
    stackRequirements:
      Manipulator: 4
      Glass: 1

- type: entity
  parent: BaseMachineCircuitboardTypan
  id: AnomalyVesselCircuitboardTypan
  name: сосуд аномалии (машинная плата)
  description: Печатная плата для сосуда аномалии.
  components:
  - type: MachineBoard
    prototype: MachineAnomalyVesselTypan
    stackRequirements:
      Manipulator: 3
      Cable: 1
      PlasmaGlass: 10

- type: entity
  parent: BaseMachineCircuitboardTypan
  id: AnomalyVesselExperimentalCircuitboardTypan
  name: экспериментальный сосуд аномалии (машинная плата)
  description: Печатная плата для экспериментального сосуда аномалии.
  components:
  - type: MachineBoard
    prototype: MachineAnomalyVesselExperimentalTypan
    stackRequirements:
      Manipulator: 3
      Cable: 5
      PlasmaGlass: 15
      MetalRod: 4

- type: entity
  parent: WeaponEnergyTurretStationMachineCircuitboardBase
  id: WeaponEnergyTurretTypanAIMachineCircuitboard
  name: охранная турель (машинная плата)
  description: Печатная плата для охранной турели.
  suffix: Тайпан, ИИ, Борги
  components:
  - type: Sprite
    sprite: _Mini/Objects/Misc/module.rsi
    state: syndicate
  - type: MachineBoard
    prototype: WeaponEnergyTurretTypanAI

- type: entity
  parent: WeaponEnergyTurretStationMachineCircuitboardBase
  id: WeaponEnergyTurretTypanProtectionMachineCircuitboard
  name: охранная турель (машинная плата)
  description: Печатная плата для охранной турели.
  suffix: Тайпан, Охрана
  components:
  - type: Sprite
    sprite: _Mini/Objects/Misc/module.rsi
    state: syndicate
  - type: MachineBoard
    prototype: WeaponEnergyTurretTypanProtection

- type: entity
  parent: WeaponEnergyTurretStationMachineCircuitboardBase
  id: WeaponEnergyTurretTypanCommandMachineCircuitboard
  name: охранная турель (машинная плата)
  description: Печатная плата для охранной турели.
  suffix: Тайпан, Командование
  components:
  - type: Sprite
    sprite: _Mini/Objects/Misc/module.rsi
    state: syndicate
  - type: MachineBoard
    prototype: WeaponEnergyTurretTypanCommand

- type: entity
  id: MaterialSiloMachineCircuitboardTypan
  parent: BaseMachineCircuitboardTypan
  name: хранилище материалов (машинная плата)
  components:
  - type: MachineBoard
    prototype: MachineMaterialSiloTypan
    stackRequirements:
      Manipulator: 4
      Cable: 1
