using System.Linq;
using Content.Client._Mini.ERT;
using Content.Shared._Mini.ERT.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Administration.UI.Tabs.AdminTab
{
    [GenerateTypedNameReferences]
    public sealed partial class ERTCallWindow : DefaultWindow
    {
        [Dependency] private readonly IEntityManager _entMan = default!;
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
        private ErtResponceSystem? _ertSystem;

        public ERTCallWindow()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _ertSystem = _entMan.System<ErtResponceSystem>();

            DeleteErtButton.OnPressed += _ => Delete();
            RefreshButton.OnPressed += _ => Refresh();
            SetArrivalButton.OnPressed += _ => SetArrival();
            SetCooldownButton.OnPressed += _ => SetCooldown();
            SetPointsButton.OnPressed += _ => SetPoints();
            SetReasonButton.OnPressed += _ => SetReason();
            ResponceErtButton.OnPressed += _ => CallErt();
            ExpectedList.OnItemSelected += OnListSelected;
            ResponceList.OnItemSelected += OnResponceListSelected;

            if (_ertSystem != null)
                _ertSystem.OnStateUpdated += PopulateFromSystem;

            // initial request
            _ertSystem?.RequestAdminState();
        }

        private string? _selectedProtoId;
        private string? _selectedRepsonceProtoId;

        private void OnListSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (args.ItemIndex < 0) return;
            _selectedProtoId = ExpectedList[args.ItemIndex].Metadata as string;

            // Отображаем цель вызова для выбранного отряда
            var state = _ertSystem?.LastState;
            if (state == null || _selectedProtoId == null)
                return;

            var entry = state.Entries.FirstOrDefault(e => e.ProtoId == _selectedProtoId);
            ReasonEdit.Text = entry?.CallReason ?? "";
        }

        private void OnResponceListSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (args.ItemIndex < 0) return;
            _selectedRepsonceProtoId = ResponceList[args.ItemIndex].Metadata as string;
        }

        private void Refresh()
        {
            _ertSystem?.RequestAdminState();
        }

        private void PopulateFromSystem()
        {
            var state = _ertSystem?.LastState;
            if (state == null) return;

            ExpectedList.Clear();

            foreach (var e in state.Entries)
            {
                ExpectedList.AddItem($"{e.Name} — {e.SecondsRemaining}s ({e.Price})", metadata: e.ProtoId);
            }

            ResponceList.Clear();

            foreach (var proto in _prototypeManager.EnumeratePrototypes<ErtTeamPrototype>())
            {
                ResponceList.AddItem($"{proto.Name} ({proto.Price})", metadata: proto.ID);
            }

            PointsEdit.Text = state.Points.ToString();
            CooldownSeconds.Text = state.CooldownSeconds.ToString();
        }

        private void SetArrival()
        {
            if (_selectedProtoId == null) return;

            if (!int.TryParse(ArrivalSeconds.Text, out var seconds))
                return;

            _ertSystem?.AdminModifyEntry(_selectedProtoId, seconds);
            Refresh();
        }

        private void Delete()
        {
            if (_selectedProtoId == null) return;
            _ertSystem?.AdminDeleteErt(_selectedProtoId);
            Refresh();
        }

        private void SetCooldown()
        {
            if (!int.TryParse(CooldownSeconds.Text, out var seconds))
                return;

            _ertSystem?.AdminSetCooldown(seconds);
            Refresh();
        }

        private void SetPoints()
        {
            if (!int.TryParse(PointsEdit.Text, out var pts))
                return;

            _ertSystem?.AdminSetPoints(pts);
            Refresh();
        }

        private void SetReason()
        {
            if (_selectedProtoId == null) return;

            _ertSystem?.AdminSetReason(_selectedProtoId, ReasonEdit.Text);
            Refresh();
        }

        private void CallErt()
        {
            if (_selectedRepsonceProtoId == null) return;

            _ertSystem?.AdminCallErt(_selectedRepsonceProtoId, ReasonResponceEdit.Text);
            Refresh();
        }
    }
}
