
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared._Mini.ERT;

namespace Content.Client._Mini.ERT.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ErtComputerShuttleWindow : DefaultWindow
    {
        private ErtComputerShuttleBoundUserInterfaceState? _lastUpdate;
        public ErtComputerShuttleWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        public void Populate(ErtComputerShuttleBoundUserInterfaceState state)
        {
            _lastUpdate = state;
        }

    }
}
