
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Client.UserInterface.Controls;
using Content.Shared._Mini.ERT;
using Content.Shared._Mini.ERT.Prototypes;

namespace Content.Client._Mini.ERT.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class ErtResponceConsoleWindow : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototype = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        private ErtResponceConsoleBoundUserInterfaceState? _lastUpdate;
        private readonly List<ErtTeamPrototype> _availableTeams = new();

        public ErtResponceConsoleWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);

            AvailableTeamsList.OnItemSelected += OnAvailableTeamsSelected;
        }

        public void Populate(ErtResponceConsoleBoundUserInterfaceState state)
        {
            _lastUpdate = state;

            AvailableTeamsList.Clear();
            _availableTeams.Clear();

            var ertSystem = _entityManager.System<ErtResponceSystem>();

            BalanceLabel.Text = Loc.GetString(
                "ert-responce-balance-label",
                ("cost", state.Money)
            );

            foreach (var team in state.Teams)
            {
                var price = ertSystem.GetErtPrice(team);

                if (_prototype.TryIndex(team, out var proto))
                {
                    AvailableTeamsList.AddItem(
                        $"{proto.Name} ({price})",
                        metadata: team.ToString()
                    );

                    _availableTeams.Add(proto);
                }
            }

            TeamDescriptionLabel.Text = string.Empty;
            ResponceTeamButton.Disabled = true;
        }

        private void OnAvailableTeamsSelected(ItemList.ItemListSelectedEventArgs args)
        {
            if (_lastUpdate == null || args.ItemIndex < 0)
            {
                ResponceTeamButton.Disabled = true;
                TeamDescriptionLabel.Text = string.Empty;
                return;
            }

            var proto = _availableTeams[args.ItemIndex];

            TeamDescriptionLabel.Text = proto.Description;

            var ertSystem = _entityManager.System<ErtResponceSystem>();
            var price = ertSystem.GetErtPrice(proto.ID);

            ResponceTeamButton.Disabled = _lastUpdate.Money < price;
        }

    }
}
